create database SIGMAXM;
GRANT ALL PRIVILEGES ON *.* TO 'sigmaxm'@'localhost' IDENTIFIED BY 'ayappa2017';

DROP TABLE IF EXISTS XM_USER;
CREATE TABLE XM_USER (
    id VARCHAR(128) PRIMARY KEY NOT NULL ,
    USERNAME VARCHAR(128) not null,
    PASSWORD VARCHAR(128) not null,
    CREATION_DATE DATE
);

INSERT INTO XM_USER(id,USERNAME,PASSWORD) values (1,'admin','$2a$12$9czIz.mIjFru/AhD2o.Pa.1n8Ro2waA52IYdedzP2V.w.9qYOgn1.' ) ;

DROP TABLE IF EXISTS  XM_AWSCONFIG ;
CREATE TABLE XM_AWSCONFIG (
    AWSCONFIG_ID VARCHAR(128) PRIMARY KEY NOT NULL ,
    AWS_ACCESS_KEY_ID VARCHAR(128) not null,
    AWS_SECRET_ACCESS_KEY VARCHAR(128) not null,
    AWS_REGION_NAME VARCHAR(128) not null,
    AWS_ACCOUNT_ID VARCHAR(128) not null,
    USER_ID VARCHAR(128) not null,
    CREATION_DATE DATE
);

DROP TABLE IF EXISTS  XM_REGISTRY;
CREATE TABLE XM_REGISTRY (
    REGISTRY_ID VARCHAR(128) PRIMARY KEY NOT NULL ,
    REGISTRY_URL VARCHAR(128) NOT NULL,
    REGISTRY_PORT INT NOT NULL,
    REGISTRY_USERNAME VARCHAR(128) NOT NULL,
    REGISTRY_PASSWORD VARCHAR(128) NOT NULL,
    USER_ID VARCHAR(128) not null,
    CREATION_DATE DATE
);

// This table is not required in the current VERSION of the software
DROP TABLE IF EXITS XM_REGISTRY_USER;
CREATE TABLE XM_REGISTRY_USER (
    REGISTRY_ID VARCHAR(128) NOT NULL ,
    id VARCHAR(128) NOT NULL );

DROP TABLE IF EXISTS XM_IMAGE;
CREATE TABLE XM_IMAGE (
    IMAGE_ID VARCHAR(128) PRIMARY KEY NOT NULL ,
    IMAGE_NAME VARCHAR(128) NOT NULL,
    REGISTRY_ID VARCHAR(128) NOT NULL
);

DROP TABLE IF EXISTS XM_SWARM;
CREATE TABLE XM_SWARM (
    SWARM_ID VARCHAR(128) PRIMARY KEY NOT NULL ,
    SWARM_NAME VARCHAR(128)  NOT NULL,
    SWARM_STATUS  VARCHAR(128) NOT NULL,
    KEYNAME VARCHAR(128) NOT NULL,
    # Manager details
    MANAGERSIZE INT  NOT NULL,
    MANAGERINSTANCETYPE VARCHAR(128) NOT NULL,
    MANAGERDISKTYPE  VARCHAR(128),
    MANAGERDISKSIZE  INT,
    # WorkerDetails details
    CLUSTERSIZE  INT NOT NULL,
    INSTANCETYPE  VARCHAR(128) NOT NULL,
    WORKERDISKTYPE  VARCHAR(128),
    WORKERDISKSIZE  INT,
    # Misc
    ENABLECLOUDWATCHLOGS  VARCHAR(128),
    ENABLESYSTEMPRUNE VARCHAR(128) ,
    USER_ID VARCHAR(128) NOT NULL,
    CREATION_DATE DATE
);


DROP TABLE IF EXISTS XM_MANAGER_DETAILS;
CREATE TABLE XM_MANAGER_DETAILS(
    MANAGER_ID VARCHAR(128) PRIMARY KEY NOT NULL ,
    SWARM_ID VARCHAR(128) ,
    MANAGER_HOSTNAME VARCHAR(128) ,
    MANAGER_IP VARCHAR(128) ,
    MANAGER_STATUS VARCHAR(128) ,
    ENGINE_VERSION VARCHAR(128) ,
    AVAILABILITY VARCHAR(128) ,
    MANAGER_STATE VARCHAR(20),
    CREATION_DATE DATE
);

DROP TABLE IF EXISTS XM_WORKER_DETAILS;
CREATE TABLE XM_WORKER_DETAILS(
    WORKER_ID VARCHAR(128) PRIMARY KEY NOT NULL ,
    SWARM_ID VARCHAR(128) ,
    WORKER_HOSTNAME VARCHAR(128) ,
    WORKER_IP VARCHAR(128) ,
    WORKER_STATUS VARCHAR(128) ,
    ENGINE_VERSION VARCHAR(128) ,
    AVAILABILITY VARCHAR(128) ,
    WORKER_STATE VARCHAR(20),
    CREATION_DATE DATE
);


DROP TABLE IF EXISTS XM_SERVICE;
CREATE TABLE XM_SERVICE(
    SERVICE_ID VARCHAR(128) PRIMARY KEY NOT NULL ,
    SERVICE_NAME VARCHAR(128) ,
    REPLICAS INT,
    SWARM_ID VARCHAR(128) ,
    IMAGE_ID VARCHAR(128) ,
    HOSTPORT INT,
    CONTAINERPORT INT,
    REGISTRY_ID VARCHAR(128),
    CREATION_DATE DATE
);

insert into users (id,username,password) VALUES(1,'$2b$12$lMLmKaGGPeoCP6M41uw2ae4XbulberuBi5pmG7vJs.TlETziXY2xK','$2b$12$1oSp3thFXbN7TDzGOMib1.Yq.vvrgtDLtWdZTypYZPU/ZZnZNSoaO');
insert into awsconfig (id,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION_NAME) VALUES(1,'AKIAJOICH7L4GJP3CBNQ','ZroQDUEvrIrjTICzjwDRt1boYDj1a3W1uQXaD8/8','us-west-2','493665568723');
INSERT INTO swarm VALUES ('arn:aws:cloudformation:us-west-2:493665568723:stack/docker1/11c53d10-e094-11e7-99fe-50d5ca789ee6','Thu, 14 Dec 2017 06:00:21 GMT',20,'yes',20,'no',2,'sigmaex2KeyPair','standard',1,'standard','t2.micro','t2.micro');
